[package]
name = "avg-played"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rosu-v2 = { git = "https://github.com/MaxOhn/rosu-v2", branch = "lazer" }
tokio = { version = "1", features = ["full"] }